#!/bin/sh

# This script runs evry 10 seconds through dwmblocks and displays a
# battery indicator in the status bar. Left click displays the battery
# status info in a form of a notification. Right click toggles threshold
# notifications (notifications shown when the power level is above 80% or 
# below 50%). A warning will always be shown when the power level is <= 20%.

if [ -d /sys/class/power_supply/BAT0 ]; then
    device="/sys/class/power_supply/BAT0"
elif [ -d /sys/class/power_supply/BAT1 ]; then
    device="/sys/class/power_supply/BAT1"
fi

datadir=~/.local/share/battery
mkdir -p $datadir
thconfig=$datadir/bat_threshold_notify

[ -f $datadir/shutdown_warning_sent ] && warning_sent=$(cat $datadir/shutdown_warning_sent) || warning_sent=0

if [ -f $thconfig ]; then
    bat_threshold_notify="$(cat $thconfig)"
else
    bat_threshold_notify=1
fi

get_info() {
    capacity=$(cat "$device"/capacity)
    status=$(cat "$device"/status)
}

notify() {
    dunstify "$1" "$2" \
        --appname="battery" \
        --urgency="$3" \
        --timeout="$4" \
        --replace="$5"
}

toggle_threshold_notifs() {
    if [ "$bat_threshold_notify" -eq 1 ]; then
        bat_threshold_notify=0
        printf "%s" $bat_threshold_notify > $thconfig
        notify "Battery: $capacity%" "Disabled threshold notifications" 1 7000 1
    else
        bat_threshold_notify=1
        printf "%s" $bat_threshold_notify > $thconfig
        notify "Battery: $capacity%" "Enabled threshold notifications" 1 7000 1
    fi
}

icon=""

get_info

if [ "$capacity" -le 75 ] && [ "$capacity" -gt 50 ]; then
    icon=""
elif [ "$capacity" -le 50 ] && [ "$capacity" -gt 30 ]; then
    icon=""
elif [ "$capacity" -le 30 ] && [ "$capacity" -gt 20 ]; then
    icon=""
elif [ "$capacity" -le 20 ]; then
    icon=""
fi

printf "%s\n" "$icon"

if [ "$bat_threshold_notify" -eq 1 ]; then
    if [ "$capacity" -ge 80 ] && [ "$status" = "Charging" ] || [ "$status" = "Full" ]; then
        notify "Batery level reached 80%" "" 1 11000 111
    elif [ "$capacity" -le 50 ] && [ "$capacity" -gt 20 ] && [ "$status" = "Discharging" ]; then
        notify "Batery level is below 50%" "" 1 11000 111
    fi
fi

if [ "$capacity" -le 10 ] && [ "$status" != "Charging" ]; then
    notify "Batery level below 10%!" "Shutting down in 2 minutes!" 2 11000 111
    if [ "$warning_sent" -eq 0 ]; then
        printf "1" > $datadir/shutdown_warning_sent 
        shutdown +2
    fi
elif [ "$capacity" -le 20 ] && [ "$status" != "Charging" ]; then
    notify "Low battery level!" "" 2 11000 111
else
    if [ "$warning_sent" -eq 1 ]; then
        shutdown -c
        printf "0" > $datadir/shutdown_warning_sent 
    fi
fi

case $BUTTON in
    1) notify "Battery: $capacity%" "$status" 1 7000 1;;
    3) toggle_threshold_notifs ;;
esac
