#!/bin/sh

# This script runs evry 10 seconds through dwmblocks and displays a
# battery indicator in the status bar. Left click displays the battery
# status info in a form of a notification. Right click toggles threshold
# notifications (notifications shown when the power level is above 80% or 
# below 50%). A warning will always be shown when the power level is <= 20%.

if [ -d /sys/class/power_supply/BAT0 ]; then
    device="/sys/class/power_supply/BAT0"
elif [ -d /sys/class/power_supply/BAT1 ]; then
    device="/sys/class/power_supply/BAT1"
fi

datadir=~/.local/share/battery
mkdir -p $datadir
thconfig=$datadir/bat_threshold_notify

if [ -f $thconfig ]; then
    bat_threshold_notify="$(cat $thconfig)"
else
    bat_threshold_notify=1
fi

get_info() {
    capacity=$(cat "$device"/capacity)
    status=$(cat "$device"/status)
}

notify() {
    dunstify "$1" "$2" \
        --appname="battery" \
        --urgency="$3" \
        --replace="$4"
}

toggle_threshold_notifs() {
    if [ "$bat_threshold_notify" -eq 1 ]; then
        bat_threshold_notify=0
        printf "%s" $bat_threshold_notify > $thconfig
        notify "Battery: $capacity%" "Disabled threshold notifications" 1 1
    else
        bat_threshold_notify=1
        printf "%s" $bat_threshold_notify > $thconfig
        notify "Battery: $capacity%" "Enabled threshold notifications" 1 1
    fi
}

icon=""

get_info

if [ "$capacity" -le 75 ] && [ "$capacity" -gt 50 ]; then
    icon=""
elif [ "$capacity" -le 50 ] && [ "$capacity" -gt 30 ]; then
    icon=""
elif [ "$capacity" -le 30 ] && [ "$capacity" -gt 20 ]; then
    icon=""
elif [ "$capacity" -le 20 ]; then
    icon=""
fi

printf "%s\n" "$icon"

if [ "$bat_threshold_notify" -eq 1 ]; then
    if [ "$capacity" -ge 80 ] && [ "$status" = "Charging" ] || [ "$status" = "Full" ]; then
        notify "Disconnect the charger" "Batery level reached $capacity%" 1 111
    elif [ "$capacity" -le 50 ] && [ "$capacity" -gt 20 ] && [ "$status" = "Discharging" ]; then
        notify "Connect the charger" "Batery level is below $capacity%" 1 111
    fi
fi

if [ "$capacity" -le 10 ] && [ "$status" != "Charging" ]; then
    # notify "Batery level below 10%!" "Shutting down in 2 minutes!" 2 11000 111
    if [ ! -f /run/systemd/shutdown/scheduled ]; then
        shutdown +2
    fi
    yad --title "Low battery level" --text "<span font='10'>Battery level is below 10%. Shutting down in 2 minutes\!</span>" --no-buttons --no-escape --width=250 --timeout=120 --timeout-indicator="bottom"
elif [ "$capacity" -le 20 ] && [ "$status" != "Charging" ]; then
    # notify "Low battery level!" "" 2 11000 111
    yad --title "Low battery level" --text "<span font='10'>Battery level is below 20%. Please connect the device to the charger.</span>" --width=250 --timeout=10
else
    if [ -f /run/systemd/shutdown/scheduled ]; then
        shutdown -c
    fi
fi

case $BLOCK_BUTTON in
    1) notify "Battery: $capacity%" "$status" 1 1;;
    3) toggle_threshold_notifs ;;
esac
