#!/bin/sh

# This script runs evry 10 seconds through dwmblocks and displays a
# battery indicator in the status bar. Left click displays the battery
# status info in a form of a notification. Right click toggles threshold
# notifications (notifications shown when the power level is above 80% or 
# below 50%). A warning will always be shown when the power level is <= 20%.

if [ -d /sys/class/power_supply/BAT0 ]; then
    device="/sys/class/power_supply/BAT0"
elif [ -d /sys/class/power_supply/BAT1 ]; then
    device="/sys/class/power_supply/BAT1"
fi

get_info() {
    capacity=$(cat "$device"/capacity)
    status=$(cat "$device"/status)
}

notify() {
    dunstify "$1" "$2" \
        --appname="battery" \
        --urgency="$3" \
        --replace="$4"
}

icon=""

get_info

if [ "$capacity" -le 75 ] && [ "$capacity" -gt 50 ]; then
    icon=""
elif [ "$capacity" -le 50 ] && [ "$capacity" -gt 30 ]; then
    icon=""
elif [ "$capacity" -le 30 ] && [ "$capacity" -gt 20 ]; then
    icon=""
elif [ "$capacity" -le 20 ]; then
    icon=""
fi

printf "%s %s\n" "$icon" "$capacity%"
