#!/bin/sh

notify() {
    dunstify --appname="clock" --replace=1 "$1" "$2"
}

icon=""
date="$(date '+%a %d %b %Y')"
hour_minute="$(date '+%H:%M')"

printf "%s %s ", "$icon" "$hour_minute"

case $BUTTON in
    1) notify "$date" "Right click to open calcurse";;
	3) st -f 'mono:pixelsize=20:antialias=true:autohint=true' -e calcurse & disown;;
esac
