#!/bin/sh
free_space_home="$(df -h | awk 'NR==4{print $4}')"
echo -e ""

case $BUTTON in
    1) dunstify --replace=1 "Free space(home): $free_space_home" "Right click to open pcmanfm";;
	3) pcmanfm $HOME & disown;;
esac
