#!/bin/sh

# Displays the current kb layout in the statusbar
# and toggles between two layouts if the icon is
# clicked. Set the initial layout in ~/.xinitrc

kb="$(setxkbmap -query | grep -oP 'layout:\s*\K\w+')" || exit 1

case $BUTTON in
	1) [ "$kb" = "hu" ] && kb="us" || kb="hu"; setxkbmap "$kb" ;;
esac

echo " $kb"
