#!/bin/sh

# Displays the current kb layout in the statusbar
# and toggles between two layouts if the icon is
# clicked. Set the initial layout in ~/.xinitrc

KBD="$(setxkbmap -query | grep layout | awk '{ print $2 }')"

[ "$KBD" == "hu" ] && KBD="us" || KBD="hu"
setxkbmap "$KBD"

echo " $KBD"
