#!/bin/sh
# memory used in percentage
echo ""
case $BUTTON in
    1) dunstify --replace=1 "Memory usage: $(free | awk '/Mem/{printf("% .f%%"), $3/$2*100} /buffers\/cache/{printf(", buffers: %.2f%"), $4/($3+$4)*100}')" "Right click to open bashtop";;
    3) st -e bashtop;;
esac
