#!/bin/bash

UNREAD=$(newsboat -x print-unread | awk '{ print $1 }')

[ "$UNREAD" -gt "0" ] && icon="" || icon=""

printf "%s\n" "$icon"

case $BUTTON in
    1) dunstify --replace=3 "$UNREAD unread news" "Ritht click to open newsboat";;
    3) st -e newsboat; pkill -RTMIN+21 dwmblocks;;
esac
