#!/bin/sh

# This script uses pactl to get the volume level, then shows it in
# a notification and displays an appropriate icon in the status bar.
# Use 'pactl list sinks' to get sink names.

case $BLOCK_BUTTON in
    1) pamixer --toggle-mute ;;
    3) setsid -f "$($TERMINAL pulsemixer)" ;;
    4) pamixer --increase 5 ;;
    5) pamixer --decrease 5 ;;
esac

notify() {
    dunstify --appname="volume" --replace=1 "$1" -h int:value:"$2" --urgency 0
}

muted=$(pamixer --get-mute)

vol=$(pamixer --get-volume)

if [ "$muted" = "true" ]; then
    icon=""
    notify "Muted ($vol%)" "$vol"
else
    if [ "$vol" -gt "70" ]; then
        icon=""
    elif [ "$vol" -gt "30" ]; then
        icon=""
    else
        icon=""
    fi

    notify "Volume $vol%" "$vol"
fi

printf "%s\n" " $icon "
