#!/usr/bin/env bash

icon=""

connect_protonvpn() {
    dunstify --appname="vpn" --replace=2 "Connecting..."
    sudo -A protonvpn c -f &>/dev/null
    get_status
    if [ "$connection" == "Connected" ]; then
        dunstify --appname="vpn" --replace=2 "Connected to protonvpn!"
        icon=""
    else 
        dunstify --appname="vpn" --replace=2 "Something went wrong."
    fi
}

disconnect_protonvpn() {
    dunstify --appname="vpn" --replace=2 "Disconnecting..."
    sudo -A protonvpn d &>/dev/null
    get_status
    if [ ! "$connection" == "Connected" ]; then
        dunstify --appname="vpn" --replace=2 "Disconnected from protonvpn!"
        icon=""
    else 
        dunstify --appname="vpn" --replace=2 "Something went wrong."
    fi
}

chose_option() {
    local option
    option=$(
        yad \
            --list \
            --title="Choose an option" \
            --column="Options" "Protonvpn" "Disconnect" \
            --height=200 \
            --width=250
    )

    option=${option/"|"/""}

    case $option in
        "Protonvpn") connect_protonvpn ;;
        "Disconnect") disconnect_protonvpn ;;
    esac
}

get_status() {
    status_protonvpn=$(protonvpn status)
    connection=$(printf "%s\n" "$status_protonvpn" | awk 'NR==1 {printf($2)}')
}

check_status() {
    dunstify --appname="vpn" --replace=2 "Checking for VPN connection." "Please wait... (Right click for options)"
    get_status

    [ "$connection" == "Connected" ] \
        && dunstify --appname="vpn" --replace=2 "$status_protonvpn" \
        && icon="" \
        && return 0

    dunstify --appname="vpn" --replace=2 "No VPN connection!"
    icon=""
}

case $BUTTON in
    1) check_status & ;;
    3) chose_option ;;
esac

printf "%s\n" $icon
