#!/bin/sh

# this script requires netcat to be installed

icon=""

notify() {
    dunstify --appname="wifi" --replace=1 "$1" "$2" --timeout="$3"
}

essid=$(iwgetid wlan0 --raw || iwgetid wlo1 --raw || iwgetid wlp2s0 --raw)
signal=$(awk 'NR==3 {printf("%.0f%%",$3*10/7)}' /proc/net/wireless)
msg=""

check_connection() {

    notify "Checking connection" "Please wait..." 0

    # checking if we are connected to a wifi network
    if [ -z "$essid" ]; then
        icon=""
        essid="Connection lost"
        signal="0%"
        msg="No WiFi network"
    else
        # checking internet connection
        if nc -z archlinux.org 443 > /dev/null 2>&1; then
            icon=""
            msg="Online"
        else
            icon=""
            msg="Offline"
        fi
    fi

    notify "$essid" "$msg, signal: $signal\nRight click for options" 7000
}

case $BUTTON in
    1) check_connection ;;
    3) setsid -f $TERMINAL -e nmtui ;;
esac

printf "%s\n" "$icon"
