#!/bin/sh

# this script requires netcat to be installed

essid=$(iwgetid wlo1 --raw || iwgetid wlp2s0 --raw)
signal=`awk 'NR==3 {printf("%.0f%%",$3*10/7)}' /proc/net/wireless`
msg=""

check_connection() {

    dunstify --appname="wifi" --replace=1 "Checking connection" "Please wait... (Right click for options)"

    # checking if we are connected to a wifi network
    if [ -z "$essid" ]; then
        echo ""
        essid="Connection lost"
        signal="0%"
        msg="No WiFi network"
    else
        # checking internet connection
        echo -e "GET http://www.google.com/ HTTP/1.0\n\n" | nc google.com 80 -w 10 > /dev/null 2>&1
        if [ $? -eq 0 ]; then
            echo ""
            msg="Online"
        else
            echo ""
            msg="Offline"
        fi
    fi

    dunstify --appname="wifi" --replace=1 "$essid" "$msg, signal: $signal"
}

check_connection &

case $BUTTON in
    3) st -e nmtui & disown ;;
esac
