#!/usr/bin/env bash

# This script reads urls from a file and pipes them into dmenu

bookmark_file="$HOME/.local/share/bookmarks"
urls=$(<$bookmark_file)

prompt=" bookmarks:"

dmenu_cmd="dmenu -lh 26 -l 10 -c -i"

url=$(printf '%s\n' "${urls[@]}" | $dmenu_cmd -p "$prompt" "$@")

# exit if the user did not pick a url
[[ -n $url ]] || exit

xdg-open "$url"
