#!/bin/sh

step=3

if [ "$1" = "inc" ]; then
    xbacklight -inc $step
elif [ "$1" = "dec" ]; then
    if [ $(xbacklight -get) -le $step ]; then
        xbacklight -set 2 # min brightness to prevent the screen from turning off
    else
        xbacklight -dec $step
    fi
fi

tvolnoti-show $(xbacklight -get) -b
