#!/bin/sh

# Send notifications if there are appointemts or todos in calcurse

num_of_todos=$(calcurse -t | grep -c '^[0-9]')
num_of_appointments_today=$(calcurse -a | grep -c '^ * ')
num_of_appointments_tomorrow=$(calcurse -a -d "$(date --date='tomorrow' +'%Y-%m-%d')" | grep -c '^ * ')

showmsg() { 
    dunstify "$1" "$2" --urgency="$3" --replace="$4" --timeout=0
}

if [ "$num_of_todos" -gt 0 ]; then
    if [ "$num_of_todos" -eq 1 ]; then
        showmsg "Calcurse" "There is 1 todo today" 1 100
    else
        showmsg "Calcurse" "There are $num_of_todos todos today" 1 100
    fi
fi

if [ "$num_of_appointments_today" -gt 0 ]; then
    if [ "$num_of_appointments_today" -eq 1 ]; then
        showmsg "Calcurse" "There is 1 appointemt today" 2 101
    else
        showmsg "Calcurse" "There are $num_of_appointments_today appointemts today" 2 101
    fi
fi

if [ "$num_of_appointments_tomorrow" -gt 0 ]; then
    if [ "$num_of_appointments_tomorrow" -eq 1 ]; then
        showmsg "Calcurse" "There is 1 appointemt tomorrow" 2 102
    else
        showmsg "Calcurse" "There are $num_of_appointments_tomorrow appointemts tomorrow" 2 102
    fi
fi
