#!/bin/bash

# This script is a dmenu_run wrapper with customized height, font and history functionality
# If the string 'sudo' is provided as the first argument and $SUDO_ASKPASS is set, the 
# selected program will be executed with sudo -A.

privileges=$1

# Find a terminal emulator to be able to launch programs in a terminal window
if [ -z "$TERMINAL_CMD" ]; then
  if [ "$(which st)" ]; then
  TERMINAL_CMD="st -e"
  elif [ "$(which terminal)" ]; then
  TERMINAL_CMD="terminal -e"
  elif [ "$(which urxvt)" ]; then
  TERMINAL_CMD="urxvt -e"
  elif [ "$(which termite)" ]; then
  TERMINAL_CMD="termite -e"
  elif [ "$(which terminator)" ]; then
  TERMINAL_CMD="terminator -e"
  elif [ "$(which gnome-terminal)" ]; then
  TERMINAL_CMD="gnome-terminal -e"
  elif [ "$(which lxterminal)" ]; then
  TERMINAL_CMD="lxterminal -e"
  elif [ "$(which sakura)" ]; then
  TERMINAL_CMD="sakura -e"
  elif [ "$(which xfce4-terminal)" ]; then
  TERMINAL_CMD="xfce4-terminal -e"
  elif [ "$(which xterm)" ]; then
  TERMINAL_CMD="xterm -e"
  elif [ "$(which kitty)" ]; then
  TERMINAL_CMD="kitty -e"
  fi
fi

# pass every command line argument to dmenu except the first (which is
# used to decide if the selected program shuld be executed with sudo)
[ $1 == "sudo" ] && prompt="[sudo]run:" || prompt="run:"
dmenu_cmd="dmenu -h 26 -fn monospace:size=12 -l 20 -g 4 -c -i -p $prompt ${@:2}"

max_recent=199 # Number of recent commands to track

cache_dir="${XDG_CACHE_HOME:-$HOME/.cache}/dmenu_hist"

recent_cache="$cache_dir/recent"
rest_cache="$cache_dir/all"

known_types=" background terminal terminal_hold "

config_dir="${XDG_CONFIG_HOME:-$HOME/.config}/dmenu_hist"
mkdir -p "$cache_dir"
mkdir -p "$config_dir"
touch "$recent_cache"

# Without this, it won't remember $type
GREP_OPTIONS='--color=never'

IFS=:
if stest -dqr -n "$rest_cache" $PATH 2>/dev/null; then
    stest -flx $PATH | sort -u | grep -vf "$recent_cache" > "$rest_cache"
fi

IFS=" "
cmd=$(cat "$recent_cache" "$rest_cache" | $dmenu_cmd) || exit

if ! grep -qx "$cmd" "$recent_cache" &> /dev/null; then
    grep -vx "$cmd" "$rest_cache" > "$rest_cache.$$"
    if -s "$rest_cache.$$"; then
        mv "$rest_cache.$$" "$rest_cache"
    else
        rm "$rest_cache.$$"
    fi
fi

if [[ ! $cmd == *[[]* ]]; then
    echo "$cmd" > "$recent_cache.$$"
    grep -vx "$cmd" "$recent_cache" | head -n "$max_recent" >> "$recent_cache.$$"
    mv "$recent_cache.$$"  "$recent_cache"
fi

# Figure out how to run the command based on the command name, disregarding
# arguments, if any.
word0=${cmd%% *}
match="^$word0$"

get_type () {
    while type=$(echo $known_types | xargs -n1 | $dmenu_cmd -g 1 -p type:); do
        [[ $known_types =~ " $type " ]] || continue
        echo "$word0" >> "$config_dir/$type"
        break
    done
    echo $type
}

if ! type=$(grep -lx "$match" -R "$config_dir"); then
    type=$(get_type)
else 
    type=${type##*/}
    if ! [[ $known_types =~ " $type " ]]; then
        rm "$config_dir/$type"
        type=$(get_type)
    fi
fi

run_as_sudo() {
    [[ "$type" = "background" ]] && exec sudo -A $cmd
    [[ "$type" = "terminal" ]] && exec sudo -A $TERMINAL_CMD "$cmd"
    [[ "$type" = "terminal_hold" ]] &&
        exec sudo -A $TERMINAL_CMD sh -c "$cmd && echo Press Enter to kill me... && read line"
}

run_as_normal() {
    [[ "$type" = "background" ]] && exec $cmd
    [[ "$type" = "terminal" ]] && exec $TERMINAL_CMD "$cmd"
    [[ "$type" = "terminal_hold" ]] &&
        exec $TERMINAL_CMD sh -c "$cmd && echo Press Enter to kill me... && read line"
}

# If the firts argument is the string 'sudo' and $SUDO_ASKPASS is set,
# run the selected program as sudo. Otherwise run with normal privileges.
if [ "$1" == "sudo" ]; then
    if [ ! -z $SUDO_ASKPASS ]; then
        run_as_sudo
    else
        echo "\$SUDO_ASKPASS is not set, running with normal privileges"
        run_as_normal
    fi
else
    run_as_normal
fi
