#!/bin/sh

# This script is a dmenu_run wrapper with customized height, font and history functionality
# If the string 'sudo' is provided as the first argument and $SUDO_ASKPASS is set, the 
# selected program will be executed with sudo -A.

# Find a terminal emulator to be able to launch programs in a terminal window
if [ -z "$TERMINAL" ]; then
    if [ "$(which st)" ]; then
        TERMINAL="st -e"
    elif [ "$(which terminal)" ]; then
        TERMINAL="terminal -e"
    elif [ "$(which urxvt)" ]; then
        TERMINAL="urxvt -e"
    elif [ "$(which termite)" ]; then
        TERMINAL="termite -e"
    elif [ "$(which terminator)" ]; then
        TERMINAL="terminator -e"
    elif [ "$(which gnome-terminal)" ]; then
        TERMINAL="gnome-terminal -e"
    elif [ "$(which lxterminal)" ]; then
        TERMINAL="lxterminal -e"
    elif [ "$(which sakura)" ]; then
        TERMINAL="sakura -e"
    elif [ "$(which xfce4-terminal)" ]; then
        TERMINAL="xfce4-terminal -e"
    elif [ "$(which xterm)" ]; then
        TERMINAL="xterm -e"
    elif [ "$(which kitty)" ]; then
        TERMINAL="kitty -e"
    fi
fi

# pass every command line argument to dmenu except the first (which is
# used to decide if the selected program shuld be executed with sudo)
[ "$1" = "sudo" ] && prompt="[sudo] run:" || prompt=" run:"
dmenu_cmd="dmenu -lh 26 -l 20 -c -i"

max_recent=200 # Number of recent commands to track

cache_dir="${XDG_CACHE_HOME:-$HOME/.cache}/dmenu_hist"

recent_cache="$cache_dir/recent"
rest_cache="$cache_dir/all"

known_types=" background terminal terminal_hold "

config_dir="${XDG_CONFIG_HOME:-$HOME/.config}/dmenu_hist"
mkdir -p "$cache_dir"
mkdir -p "$config_dir"
touch "$recent_cache"

# Without this, it won't remember $type
#GREP_OPTIONS='--color=never'

IFS=:
if stest -dqr -n "$rest_cache" $PATH 2>/dev/null; then
    stest -flx $PATH | sort -u | grep -vf "$recent_cache" > "$rest_cache"
fi

IFS=" "
cmd=$(cat "$recent_cache" "$rest_cache" | $dmenu_cmd -p "$prompt") || exit

if ! grep -qx "$cmd" "$recent_cache" > /dev/null 2>&1; then
    grep -vx "$cmd" "$rest_cache" > "$rest_cache.$$"
    if [ -s "$rest_cache.$$" ]; then
        mv "$rest_cache.$$" "$rest_cache"
    else
        rm "$rest_cache.$$"
    fi
fi

case $cmd in
    '[') 
        exit
        ;; 
    *)
        echo "$cmd" > "$recent_cache.$$"
        grep -vx "$cmd" "$recent_cache" | head -n "$max_recent" >> "$recent_cache.$$"
        mv "$recent_cache.$$"  "$recent_cache"
        ;;
esac

# Figure out how to run the command based on the command name, disregarding
# arguments, if any.
word0=${cmd%% *}
match="^$word0$"

get_type () {
    while type=$(echo "$known_types" | xargs -n1 | $dmenu_cmd -p type:); do
        test "${known_types#*$type}" != "$known_types" || continue
        echo "$word0" >> "$config_dir/$type"
        break
    done
    printf "%s" "$type"
}

if ! type=$(grep -lx "$match" -R "$config_dir"); then
    type=$(get_type)
else 
    type=${type##*/}
    if ! [ "${known_types#*$type}" != "$known_types" ]; then
        rm "$config_dir/$type"
        type=$(get_type)
    fi
fi

run_as_sudo() {
    [ "$type" = "background" ] && sudo -A "$cmd"
    [ "$type" = "terminal" ] && sudo -A $TERMINAL "$cmd"
    [ "$type" = "terminal_hold" ] &&
        exec sudo -A $TERMINAL sh -c "$cmd && echo Press Enter to quit... && read line"
}

run_as_normal() {
    [ "$type" = "background" ] && "$cmd"
    [ "$type" = "terminal" ] && $TERMINAL "$cmd"
    [ "$type" = "terminal_hold" ] &&
        exec $TERMINAL sh -c "$cmd && echo Press Enter to kill me... && read line"
}

# If the firts argument is the string 'sudo' and $SUDO_ASKPASS is set,
# run the selected program as sudo. Otherwise run with normal privileges.
if [ "$1" = "sudo" ]; then
    if [ -n "$SUDO_ASKPASS" ]; then
        run_as_sudo
    else
        echo "\$SUDO_ASKPASS is not set, running with normal privileges"
        run_as_normal
    fi
else
    run_as_normal
fi
