#!/bin/sh

source_dir="$HOME/source"

# dmenu settings
prompt=" git projects:"
dmenu_cmd="dmenu -lh 26 -l 20 -c -i $@"

# find a terminal emulator
if [ -z "$TERMINAL" ]; then
    if [ "$(which st)" ]; then
        TERMINAL="st -e"
    elif [ "$(which terminal)" ]; then
        TERMINAL="terminal -e"
    elif [ "$(which urxvt)" ]; then
        TERMINAL="urxvt -e"
    elif [ "$(which termite)" ]; then
        TERMINAL="termite -e"
    elif [ "$(which terminator)" ]; then
        TERMINAL="terminator -e"
    elif [ "$(which gnome-terminal)" ]; then
        TERMINAL="gnome-terminal -e"
    elif [ "$(which lxterminal)" ]; then
        TERMINAL="lxterminal -e"
    elif [ "$(which sakura)" ]; then
        TERMINAL="sakura -e"
    elif [ "$(which xfce4-terminal)" ]; then
        TERMINAL="xfce4-terminal -e"
    elif [ "$(which xterm)" ]; then
        TERMINAL="xterm -e"
    elif [ "$(which kitty)" ]; then
        TERMINAL="kitty -e"
    fi
fi

list=$(ls "$source_dir"/* -d)

# replace $HOME with ~ for every list item
list=$(echo "$list" | sed "s\\$HOME\~\g")

to_open=$(printf "%s\n" "$list" | $dmenu_cmd -p "$prompt")

# exit if the user did not pick an item
[ -n "$to_open" ] || exit

# undo the replacement for the picked item (otherwise won't open correctly)
to_open=$(echo "$to_open" | sed "s\~\\$HOME\g")

$TERMINAL lazygit -p "$to_open"
