#!/bin/sh

test -z "$(which ueberzug)" &&
	exec vifm "$@" && exit

test -z "$DISPLAY" &&
	exec vifm "$@" && exit

cleanup() {
    rm "$FIFO_UEBERZUG"
    pkill -P $$ >/dev/null
}

! test -d "$HOME/.cache/vifm" && mkdir -p "$HOME/.cache/vifm"
export UEBERZUG_FIFO="$HOME/.cache/vifm/ueberzug-${PPID}" || return 1
mkfifo "$UEBERZUG_FIFO"
trap 'rm $UEBERZUG_FIFO 2>/dev/null && unset UEBERZUG_FIFO;
pkill -P $$ 2>/dev/null' EXIT
tail -f "$UEBERZUG_FIFO" | ueberzug layer --silent --parser simple --loader thread &! \
    command vifm "$@"
