#!/bin/sh

CACHE="$HOME/.cache/vifm/thumbnail.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$PWD/$6")" | sha256sum | awk '{print $1}'))"

pclear() {
	printf "action\tremove\tidentifier\tpreview\n" > "$UEBERZUG_FIFO"
}

image() {
	{
		printf 'action\tadd\tidentifier\tpreview\t'
		printf 'x\t%d\ty\t%d\t' "$2" "$3"
		printf 'width\t%d\theight\t%d\t' "$4" "$5"
		printf 'path\t%s\n' "$6"
	} > "$UEBERZUG_FIFO"
}

main() {
    case "$1" in
        "clear")
			pclear "$@"
			;;
        "draw")
			FILE="$PWD/$6"
			image "$1" "$2" "$3" "$4" "$5" "$FILE"
			;;
        "video")
			[ ! -f "$CACHE" ] && \
				ffmpegthumbnailer -i "$6" -o "${CACHE}.jpg" -s 0 -q 5
			image "$1" "$2" "$3" "$4" "$5" "${CACHE}.jpg"
			;;
        "epub")
			[ ! -f "$CACHE" ] && \
				epub-thumbnailer "$6" "$CACHE" 1024
			image "$1" "$2" "$3" "$4" "$5" "$CACHE"
			;;
        "pdf")
			[ ! -f "${CACHE}.jpg" ] && \
				pdftoppm -jpeg -f 1 -singlefile "$6" "$CACHE"
			image "$1" "$2" "$3" "$4" "$5" "${CACHE}.jpg"
			;;
        "audio")
			[ ! -f "${CACHE}.jpg" ] && \
				ffmpeg -i "$6" "${CACHE}.jpg" -y > /dev/null 2>&1
			image "$1" "$2" "$3" "$4" "$5" "${CACHE}.jpg"
			;;
        "font")
			[ ! -f "${CACHE}.jpg" ] && \
				fontpreview -i "$6" -o "${CACHE}.jpg"
			image "$1" "$2" "$3" "$4" "$5" "${CACHE}.jpg"
			;;
        *)
			echo "Unknown command: " "$@"
			;;
    esac
}
main "$@"
