#!/bin/sh

# script to make extracting archives easier

archive=$1

mkxdir() {
    xdir=${archive%$1}  # retain the part before the extention
    mkdir "$xdir"
}

if [ -f "$1" ] ; then
    case $1 in
        *.zip)       
            mkxdir ".zip"
            unzip "$1" -d "$xdir"
            ;;
        *.tar.gz)
            mkxdir ".tar.gz"
            tar xzf "$1" -C "$xdir"
            ;;
        *.tar.bz2)   
            mkxdir ".tar.bz2"
            tar xjf "$1" -C "$xdir"
            ;;
        *.tar)
            mkxdir ".tar"
            tar xf "$1" -C "$xdir"
            ;;
        *.tbz2)
            mkxdir ".tbz2"
            tar xjf "$1" -C "$xdir"
            ;;
        *.tgz)
            mkxdir ".tgz"
            tar xzf "$1" -C "$xdir"
            ;;
        *.rar)
            mkxdir ".rar"
            unrar e "$1" "$xdir"
            ;;
        *.7z)        
            7z x "$1" -o "$xdir"       
            ;;
        *.gz)
            gunzip "$1"
            ;;
        *.bz2)
            bunzip2 "$1"
            ;;

        *) 
            echo "'$1' cannot be extracted via xtract" 
            ;;
    esac
else
    echo "'$1' is not a valid file"
fi
